[package]
name = "humility-cmd-probe"
version = "0.1.0"
edition = "2021"
description = "probe for any attached devices"

[dependencies]
clap.workspace = true
anyhow.workspace = true
log.workspace = true
num-traits.workspace = true
colored.workspace = true

humility.workspace = true
humility-arch-arm.workspace = true
humility-cortex.workspace = true
humility-cmd.workspace = true
