[package]
name = "humility-cmd-diagnose"
version = "0.1.0"
edition.workspace = true
description = "analyze a system to detect common problems"

[dependencies]
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-doppel.workspace = true
humility-jefe.workspace = true
