[package]
name = "humility-cmd-stackmargin"
version = "0.1.0"
edition.workspace = true
description = "calculate and print stack margins by task"

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
humility-cli = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
