[package]
name = "humility-cmd-rpc"
version = "0.1.0"
edition = "2021"
description = "manipulate HIF execution"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
humility-cmd-hiffy = { path = "../hiffy" }
humility-cmd-net = { path = "../net" }

hif = { git = "https://github.com/oxidecomputer/hif" }
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = { version = "3.0.12", features = ["derive", "env"] }
colored = "2.0.0"
indexmap = "1.7"
libc = "0.2"
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"
zerocopy = "0.6.1"
