[package]
name = "humility-cmd-validate"
version = "0.1.0"
edition = "2021"
description = "validate presence and operation of devices"

[dependencies]
hif.workspace = true
clap.workspace = true
colored.workspace = true
anyhow.workspace = true
parse_int.workspace = true
idol.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
humility-i2c.workspace = true
