[package]
name = "humility-cmd-sensors"
version = "0.1.0"
edition = "2021"
description = "query sensors and sensor data"

[dependencies]
hif.workspace = true
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true
indexmap.workspace = true
itertools.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-doppel.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
