[package]
name = "humility-cmd-tasks"
version = "0.1.0"
edition.workspace = true
description = "list Hubris tasks"

[dependencies]
clap.workspace = true
anyhow.workspace = true
num-traits.workspace = true
log.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-arch-arm.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-doppel.workspace = true
humility-stack.workspace = true
