[package]
name = "humility-cmd-jefe"
version = "0.1.0"
edition = "2021"
description = "influence jefe externally"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
structopt = "0.3"
anyhow = { version = "1.0.44", features = ["backtrace"] }
parse_int = "0.4.0"
log = {version = "0.4.8", features = ["std"]}
