[package]
name = "humility-cmd-tofino-eeprom"
version = "0.1.0"
edition.workspace = true
description = "read and write to the Tofino SPI EEPROM"

[dependencies]
anyhow.workspace = true
clap.workspace = true
indicatif.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
