[package]
name = "humility-cmd-flash"
version = "0.1.0"
edition.workspace = true
description = "flash archive onto attached device"

[dependencies]
humility = { workspace = true }
humility-cortex = { workspace = true }
humility-cmd = { workspace = true }
humility-cli = { workspace = true }
humility-probes-core = { workspace = true }
cmd-auxflash = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
parse_int = { workspace = true }
num-traits = { workspace = true }
tempfile = { workspace = true }
ron = { workspace = true }
path-slash = { workspace = true }
srec = { workspace = true }
ihex = { workspace = true }
goblin = { workspace = true }
