[package]
name = "humility-cmd-flash"
version = "0.1.0"
edition = "2021"
description = "flash archive onto attached device"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cortex = { path = "../../humility-arch-cortex" }
humility-cmd = { path = "../../humility-cmd" }
humility-cmd-auxflash = { path = "../auxflash" }
clap = { version = "3.0.12", features = ["derive", "env"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
parse_int = "0.4.0"
log = {version = "0.4.8", features = ["std"]}
num-traits = "0.2"
serde = { version = "1.0.126", features = ["derive"] }
tempfile = "3.3"
ron = "0.7"
path-slash = "0.1.4"
srec = "0.2"
ihex = "3.0"
goblin = "0.2"
regex = "1.5.5"
