[package]
name = "humility-cmd-host"
version = "0.1.0"
edition = "2021"
description = "Pretty-printing of host state"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
ipcc-data.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-doppel.workspace = true
humility-log.workspace = true
