[package]
name = "humility-cmd-pmbus"
version = "0.1.0"
edition.workspace = true
description = "scan for and read PMBus devices"

[dependencies]
hif.workspace = true
pmbus.workspace = true
clap.workspace = true
anyhow.workspace = true
colored.workspace = true
indexmap.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-cli.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
humility-i2c.workspace = true
humility-idol.workspace = true
humility-pmbus.workspace = true
