[package]
name = "humility-cmd-ibc"
version = "0.1.0"
edition.workspace = true
description = "interface to the BMR491 power regulator"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
parse_int.workspace = true
zerocopy.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-idol.workspace = true
humility-hiffy.workspace = true

hif.workspace = true
idol.workspace = true
pmbus.workspace = true
