[package]
name = "humility-cmd-vsc7448"
version = "0.1.0"
edition = "2021"
description = "VSC7448 operations"

[dependencies]
anyhow = { version = "1.0.44", features = ["backtrace"] }
hif = { git = "https://github.com/oxidecomputer/hif" }
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
humility-cmd-spi = { path = "../spi" }
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"
structopt = "0.3"
vsc7448-info = { git = "https://github.com/oxidecomputer/vsc7448.git" }
vsc7448-types = { git = "https://github.com/oxidecomputer/vsc7448.git" }
