[package]
name = "humility-cmd-spi"
version = "0.1.0"
edition = "2021"
description = "SPI reading and writing"

[dependencies]
hif.workspace = true
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
