[package]
name = "humility-cmd-qspi"
version = "0.1.0"
edition = "2021"
description = "QSPI status, reading and writing"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
hif = { git = "https://github.com/oxidecomputer/hif" }
structopt = "0.3"
anyhow = { version = "1.0.44", features = ["backtrace"] }
parse_int = "0.4.0"
indicatif = "0.15"
log = {version = "0.4.8", features = ["std"]}
