[package]
name = "humility-cmd-rendmp"
version = "0.1.0"
edition = "2021"
description = "Renesas digital muliphase controller operations"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
hif = { git = "https://github.com/oxidecomputer/hif", branch = "expand-collect-u32" }
pmbus = { git = "https://github.com/oxidecomputer/pmbus" }
clap = { version = "3.0.12", features = ["derive", "env"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
indicatif = "0.15"
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"
num-traits = "0.2"
num-derive = "0.3"
