[package]
name = "humility-cmd-dump"
version = "0.1.0"
edition.workspace = true
description = "generate Hubris dump"

[dependencies]
anyhow.workspace = true
clap.workspace = true
goblin.workspace = true
hubpack.workspace = true
humpty.workspace = true
indexmap.workspace = true
indicatif.workspace = true
log.workspace = true
lzss.workspace = true
num-traits.workspace = true
parse_int.workspace = true
zerocopy.workspace = true
zip.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-dump-agent.workspace = true
humility-arch-arm.workspace = true
