[package]
name = "humility-cmd-update"
version = "0.1.0"
edition = "2021"
description = "apply an update"

[dependencies]
hif.workspace = true
anyhow.workspace = true
clap.workspace = true
parse_int.workspace = true
log.workspace = true
indicatif.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
