[package]
name = "humility-cmd-vpd"
version = "0.1.0"
edition.workspace = true
description = "read or write vital product data (VPD)"

[dependencies]
hif.workspace = true
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true
indexmap.workspace = true
idol.workspace = true
tlvc.workspace = true
tlvc-text.workspace = true
zerocopy.workspace = true
indicatif.workspace = true
serde.workspace = true
ron.workspace = true

humility-cmd.workspace = true
humility-cli.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
humility.workspace = true
