[package]
name = "humility-cmd-registers"
version = "0.1.0"
edition.workspace = true
description = "print Hubris registers"

[dependencies]
clap.workspace = true
anyhow.workspace = true
num-traits.workspace = true

humility.workspace = true
humility-arch-arm.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-cortex.workspace = true
humility-stack.workspace = true
