[package]
name = "humility-cmd-registers"
version = "0.1.0"
edition = "2021"
description = "print Hubris registers"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cortex = { path = "../../humility-arch-cortex" }
humility-cmd = { path = "../../humility-cmd" }
clap = { version = "3.0.12", features = ["derive", "env"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
log = {version = "0.4.8", features = ["std"]}
num-traits = "0.2"
strum = "0.24.1"
goblin = "0.2.1"
