[package]
name = "humility-cmd-extract"
version = "0.1.0"
edition.workspace = true
description = "extract all or part of a Hubris archive"

[dependencies]
anyhow.workspace = true
clap.workspace = true
zip.workspace = true

humility-cli.workspace = true
humility-cmd.workspace = true
humility-log.workspace = true
